enum UserConstants {
    USERNAME = "sevetse13",
    USERNAME2 = "groupFOUR",
    EMAIL = "sevetse@hotmail.com",
    EMAIL2 = "group4@hotmail.com",
    PASSWORD = "1234567",
    TITLE = "Hello World!",
    POSTTYPE1 = "text",
    POSTTYPE2 = "link",
    POSTCONTENT = "Hello World!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    POSTCOMMENTINVALID = "ola",
    POSTCONTENTWITHLINK = "https://www.google.com",
    POSTCOMMENT = "Hello World!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    POSTCOMMENTWITHEMOJI = "Hello World!!!!!!!!!!!!!!!!!!!!!!!!!!!😀",
    POSTCOMMENTONLYEMOJI = "😀",
    POSTCOMMENTWITHUNICODE = "NͫOͬ",
    EXPIREDTOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF2ZXJhZ2UyQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYXZlcmFnZTIiLCJ1c2VySWQiOiI5ZWZlNGZlMy1hNDhmLTRlNTItYWJmMi00N2NjODIzNjYwMTciLCJhZG1pblVzZXIiOmZhbHNlLCJpc0VtYWlsVmVyaWZpZWQiOmZhbHNlLCJpYXQiOjE3MDI1NDY2MDUsImV4cCI6MTcwMjU0NjkwNX0.J9MTxzfkpCY0egRdbKJ0txmg369ULkx3ADbLpv9O0BY",
    INVALIDCOMMENTID = "5f9f9f9f9f9f9f9f9f9f9f9f",
    INVALIDSLUG = "111",
    COMMENTWITHSPECIALCHARACTERS = "Hello World!!!!!!!!!!!!!!!!!!!!!!!!!!!@#$%¨&*()_+",
    COMMENTREPLY = "Comment Reply - work in progress!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    COMMENTREPLYWITHLINK = "https://www.google.com",
    EMPTYSTRING = "",
    EMPTYCOMMENT = "",
    EMPTYTOKEN = "",
    EMPTYID = "",
}

export default UserConstants;